### ISSUE TITLE
Aanmeldproces activity diagram is niet duidelijk

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#107]
Input van @sander-su

- Niet alle activitieiten staan in de juiste lane; sommige activiteiten moeten worden opgesplitst.
- Overweeg 2 sequenz diagrammen; 1 voor de registratie en 1 voor de installatie
- Maak duidelijk wat registratie en installatie betekenen.

**Comment by Laurentjg** [comment]
Dit is een juiste constatering. Een evaluatie leert dat dit echter **nog** geen invloed heeft op de specificatie. Dit wordt zeer relevant bij de detail-specificatie. Daarom milestone toegevoegd. @bw-alliander  mee eens?

**Comment by bw-alliander** [comment]
2 diagrammen is een goed idee, daar wordt het denk ik flink duidelijker van.

Wellicht zijn flowdiagrammen voor de individele services een goed idee?

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#21
