### ISSUE TITLE
Orginele plaatjes uploaden

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#11]
@Laurentjg kan je de originele plaatjes ook uploaden? bijvoorbeeld in ppt formaat (afhankelijk van de gebruikte techniek). Hiermee kunnen andere de plaatjes evt verbeteren/aanvullen.

**Comment by Laurentjg** [comment]
Powerpoint met originele plaatjes toegevoegd onder ./assets
