### ISSUE TITLE
Testplatform planning en inrichting

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#12]
Als de interface is gespecificeerd moet bepaald worden wanneer precies en testplatform gereed moet staan om de interfaces van de devices te kunnen testen. 
Daarna moet dit platform of deze tool gereed worden gemaakt als referentie voor de interfaces.

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#12
