### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#18]
Hoe wordt 't duidelijk welke versie van de interface specificatie wordt gebruikt?

**Comment by Laurentjg** [comment]
De eerste "freeze" zal zijn op 20 maart ter goedkeuring, met op 29 maart na mogelijk nog kleine tekstuele aanpassingen een nieuwe "freeze". Deze zouden een versienummer moeten krijgen en ook via GitDoc als PDF worden geborgd. @Sander3003 op dat moment is wellicht een Fork de juiste methode?

**Comment by Sander3003** [comment]
Naast de versie van dit document is het misschien ook handig om de versie van de interface via de interface zelf beschikbaar te maken. Software die gebruikt maakt van de interface weet dan wat de mogelijkheden zijn.

Voor github kan men een z.g. release maken: https://help.github.com/articles/creating-releases/

**Comment by Laurentjg** [comment]
@Sander3003 : Ja, versie ook via de interface ontsluiten. Opnemen in informatiemodel.

**Comment by Sander3003** [comment]
Onderdeel van detail specificatie.

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#13
