### ISSUE TITLE
Uitwisselbaarheid

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#19]
Een requirement rondom de uitwisselbaarheid van apparaten ontbreekt. Zonder deze uitwisselbaarheid kan het zijn dat bij elke device leverancier specifieke configuraties nodig zijn (ondanks dat grote dele gestandaardiseerd zijn).

2nd DC IEC TR 61850-7-6 spreekt over interoperability om dit te bereiken.

**Comment by Laurentjg** [comment]
Requirement 21 toegevoegd. @Sander3003 , graag review en daarna issue sluiten

**Comment by Sander3003** [comment]
Akkoord
