### ISSUE TITLE
Opstellen initiële sequence diagrammen

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#22]
...op basis van word-versie databehoeftes.
Kijk hiervoor ook bij Bijlage 3, functie en business keuzes en hoofdstuk 3.3.
Output is een sequence digram als specificatie en kan worden aangepast indien het beter in een standaard past. Het geeft echter de basisbehoefte weer.

**Comment by Sander3003** [comment]
Eerste opzet voor de registratie: https://netbeheernederland.gitbooks.io/interfacespecificatie-elektriciteit/content/informatie-specificatie/registratie_protocol.html

**Comment by Sander3003** [comment]
Verwerkt in hoofdstukken 5.1.
