### ISSUE TITLE
Privacy check

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#26]
Voor het vrijgeven van de specificatie moet de privacy-aspecten m.b.v. de interface worden gecontroleerd. De privacy in de "centrale" systemen moet later ook worden geborgd in de centrale systemen, maar is buiten scope van dit vraagstuk.

**Comment by Sander3003** [comment]
Item in principe buiten scope. Open laten staan voor de focus op privacy van het geheel.

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#15
