### ISSUE TITLE
Check op ongewenste afmeldingen

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#28]
Hoe voorkomen we dat een grapjas alle productie elektriciteit eenheden afmeld?

Idee: check op beschikbaarheid, alleen gecertificeerde instanties mogen afmelden

**Comment by Sander3003** [comment]
https://netbeheernederland.gitbooks.io/interfacespecificatie-elektriciteit/content/informatie-specificatie/gerelateerde_business-_en_systeemprocessen.html

De systeembeheerder hier zelf checks voor inbouwen. Het afmelden van elektriciteitsproductie eenheden kan niet worden gestart via de interface specificatie.

**Comment by Laurentjg** [comment]
Aangezien deze discussie van belang wordt voor "centrale" systemen, heb ik dit aan de "milestones" toegepast.

**Comment by koenver** [comment]
Sander, is de aanmeldservice specifiek op andere servers (eigen IP) tov de aanstuurservers ?  
(ik vernam bij een Duitse netwerkbeheerder dat men dat bewust zo had ingericht).  Dit  zou het systeem robuuster maken tegen grapjassen (DDOSsen ed)

**Comment by Sander3003** [comment]
@bw-alliander kan jij antwoord geven op de vraag van Koen?

**Comment by bw-alliander** [comment]
Mijn voorstel zou zijn dat afmelden via de QR code op het apparaat moet.

Dit code is het serienummer van het device, ondertekend met een fabrikantsleutel, deze zijn dus alleen door de fabrikant na te maken.
Serienummers zijn opvolgend, maar de ondertekening is niet door een grapjas na te maken.

Dit maakt de implementatie ook erg makkelijk, als je het QR code scanned krijg je de aanmeldpagina als een apparaat niet aangemeld is, en een statuspagina met afmeldknop als hij wel aangemeld is.

Wel bij de gebruiker/fabrikant vermelden dat indien een apparaat publiek hangt dat het QR code niet zichtbaar moet zitten, maar een grapjas die ze allemaal afloopt is moeilijk als hij dat fysiek zou moeten.

Daarnaast stuur je netjes een afmeldmail natuurlijk, dan weet de gebruiker als een grapjas zijn qr code toch gevonden heeft :)

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#16
