### ISSUE TITLE
Lifecycle elektriciteit-productie-eenheden en de interface specificatie

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#32]
Hoe voorkomen we dat bij een nieuwe interface specificatie (bijvoorbeeld een betere encryptie methode), delen van de elektriciteit-productie-eenheden moeten worden vervangen?

**Comment by Laurentjg** [comment]
Het toestaan van het toepassen van een extra gateway, die op zichzelf gemakkelijker kan worden vervangen is hier een oplossing. Anderzijds als een software-update binnen de hardware van een leverancier past is dit mogelijk nog efficiënter. Echter kan er ook nog rekening worden gehouden met de levensduur van de regelapparatuur zoals PV converters. Als blijkt dat deze redelijk snel moeten worden vervangen door veroudering, dan zal er een maatschappelijke kosten / risico afweging gemaakt moeten worden hoelang met de oude specificaties mag worden gewerkt.

**Comment by Sander3003** [comment]
Keuze gemaakt en verwerkt in specificatie.
