### ISSUE TITLE
Levensduur elektriciteit-productie-eenheden-RfG

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#33]
Hoevaak mag deze interface specificatie vervangen worden?

**Comment by Laurentjg** [comment]
Eén keer per drie jaar mag deze worden aangepast. Het geldt nu voor nieuwe productie-eenheden die in het net worden geïnstalleerd. Om te voorkomen dat leveranciers hun hardware continue moeten aanpassen wordt de toepassing van gateways toe te staan, zoals momenteel geformuleerd in [Bijlage 3, keuze "De mogelijkheid om de interface te integreren in bestaande elektriciteitsproductie-eenheden, als ook het toepassen van gateways"](https://netbeheernederland.gitbooks.io/interfacespecificatie-elektriciteit/content/bijlage_3_gemaakte_keuzes_en_toelichting.html).

**Comment by Sander3003** [comment]
Gateways lijken me een goede oplossing.
