### ISSUE TITLE
Afschakelen: geen productie meer of geen teruglevering meer?

### ISSUE THREAD

**Issue by MiD4All** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#35]
zonder de codes gelezen te hebben:
blijkbaar moet een signaal gegeven kunnen worden aan een aansluiting of apparaat achter de aansluiting dat gestopt moet worden met productie. Of gaat het om het stoppen van teruglevering aan het net?
(a) bij stoppen productie betekent het dat al het verbruik op de aansluiting daarna uit het net geleverd moet worden. 
(b) bij stoppen teruglevering op het net betekent het dat de aangeslotene ook ander acties mag ondernemen.

Interessant voor deze vraag is wellicht op welke manier naar een teruglever apparaat gekeken wordt irt de elektrische aansluiting (denk ook aan begrippen als eigen verbruik, opwek, meerdere leveranciers op één aansluiting)

**Comment by Laurentjg** [comment]
Het volledige antwoord is lastiger (zie onderstaand), maar in het kort komt het er op neer dat het sturen op een net-aansluitpunt zeker voordelen heeft. Dit kan alleen plaatsvinden als we ook individuele devices kunnen sturen. Voor nu, met korte tijdslijnen, stellen we voor te kiezen om de device-sturing uit te werken waarbij het ontwerp open is om ook later invulling te geven aan het sturen van een aansluiting, waarna de devices intern (achter de aansluiting) wordt afgeregeld. De interface en de achterliggende processen moet dit dus uiteindelijk wel kunnen ondersteunen.

Het langere antwoord: De codes zeggen: De elektriciteitsproductie-eenheid ...waarmee het werkzaam uitgangsvermogen binnen vijf seconden naar nul kan worden gereduceerd ...
Hierin is de **elektriciteitsproductie-eenheid** gedefinieerd als "_een synchrone elektriciteitsproductie-eenheid of een power park module_" en **power park module** is "_een eenheid of een verzameling van eenheden die elektriciteit opwekt, die ofwel niet- synchroon ofwel via vermogenselektronica met het systeem verbonden is en één aansluitpunt heeft met een transmissiesysteem, een distributiesysteem, inclusief een gesloten distributiesysteem, of een HVDC-systeem_". Hieruit lijkt (nog te bevestigen) dat er uiteindelijk ook voor één aansluitpunt moet worden kunnen gestuurd. 

Dit issue blijf in ieder geval openstaan tot 28 februari.

**Comment by Sander3003** [comment]
Bij IEC61850 is gekozen voor de DCRT logical node. Deze voorzien in het besturen van 1 of meerdere productie eenheden/verbruikers. Dit kan gecontroleerd worden in de detail specificatie.

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#18
