### ISSUE TITLE
fases meenemen in specficatie?

### ISSUE THREAD

**Issue by MiD4All** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#36]
Het is niet onredelijk om te stellen dat het (LS) net bestaat uit 3 verschillende netwerken.  Moet deze specificatie in deze fase daar al rekening mee houden of op zijn minst verwijzen dat dit in de toekomst opgenomen kan gaan / gaat worden.

Hoewel veel van de apparatuur wellicht op 3 fase werkt lijkt het mij belangrijk om hier in de specificatie expliciet rekening mee te houden. Problemen op één van de fases kan leiden tot de sturing. En die sturing kan dan ook nog eens één van de fases betreffen.
 
- impact op stuur informatie
- impact op plaats / vervanging informatie
- impact op type informatie (wat is wel / niet mogelijk op fase niveau)

**Comment by Laurentjg** [comment]
En eraan toegevoegd, dat bij het installeren van de productie-eenheden vrijwel onmogelijk is om te garanderen  op welke fase (van de drie) het wordt aangesloten (bij LS-normale huisaansluiting). Tenzij deze informatie bij de Netbeheerder bekend is (geregistreerd of gemeten).  Voor de rest is dit waar.

**Comment by koenver** [comment]
Ik denk dat fase vastlegging , niet zoveel impact heeft . (zodra de opwek al boven de grofweg 3kW piek komt) dan zal deze al 3 fasig moeten worden  aangesloten.  Dus grofweg boven de  12 zonnepanelen zit je al snel met een 3 fase en dus symmetrische belasting

**Comment by Sander3003** [comment]
Om bovengenoemde reden worden fases niet meegenomen in de specificatie.
