### ISSUE TITLE
Bepalen update proces, rollen en triggers hierin

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#40]
Eisen, uitvoering en afspraken rondom updates firmware en parameters definiëren.

**Comment by Laurentjg** [comment]
De specificatie is geschreven naar (in onze interpretatie) de geest van de RfG, namelijk dat zoveel mogelijk aan de markt wordt overgelaten m.b.t. het sturen van de productie-eenheden. Dit betekent nog niet dat de bovenstaande vraag hiermee volledig is ingevuld. Er staat in hoofdstuk 5.4. beschreven dat firmware updates door de leverancier moet worden verzorgd. Vervolgafspraken zijn onderdeel van een vervolgtraject: "regelgeving aangepast".

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#25
