### ISSUE TITLE
Motivatie voor procumenten om interface te gebruiken

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#42]
Er is momenteel geen regelgeving of direct voordeel voor procumenten om hun elektriciteitproductie-eenheden met de interface aan te sluiten. Ze zullen dit alleen in sommige situaties vrijwillig doen, bijvoorbeeld getriggered door het sowieso aansluiten i.v.m. apps van converterleveranciers. Daarnaast zal een enkeling de noodzaak ervan inzien voor de stabiliteit van het elektriciteitsnet te kunnen managen. Verwacht wordt dat de overgrote meerderheid deze noodzaak (nog) niet inziet. Wat ontbreekt is een uitwerking tussen Klant&Markt, ACM en eventueel overige partijen hoe de huidige en toekomstige procumenten worden gemotiveerd om de interface aan te sluiten zodat de net-systeemstabiliteit blijft gewaarborgd.

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#26
