### ISSUE TITLE
Wat willen we voor de schedules definiëren? 

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#5]
- Hoelang vooruit in relatie tot het autonoom (zonder communicatie) kunnen werken?
- Gebruik van dezelfde mechanismes als FNN Steuerbox (DE)

**Comment by Sander3003** [comment]
Hebben we überhaupt schedules nodig? De Steuerbox specificeert het aantal schema's die gebruikt moeten kunnen worden op het device.

**Comment by Laurentjg** [comment]
Als we er vanuit gaan dat de devices af en toe tijdelijk niet communicatief zijn (b.v. DLS storing), dan zorgt dit voor een verhoogde autonomie om alles lokaal stabiel te houden o.b.v. het voorspelbare gedrag in dit gebied. Zie ook [business kaders](https://netbeheernederland.gitbooks.io/interfacespecificatie-elektriciteit/content/architectuur_uitgangspunten/businesskader.html) in het hoofdstuk "Praktische overwegingen RfG Type A"

**Comment by Sander3003** [comment]
Keuze gemaakt: toepassen schedules op basis van IEC61850-90-10.
