### ISSUE TITLE
Ethernet interface specificeren

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#51]
Vraag vanuit security: om de optie open te laten, de grotere eenheden later ook direct met DSO/TSO te kunnen verbinden, moeten grotere eenheden een Ethernet interface hebben. Deze kan dan direct met DSO/TSO netwerk verbinden.

**Comment by Sander3003** [comment]
Is voorzien in 5.5 waarbij tevens ook de het type connector wordt gespecificeerd (rj45).
