### ISSUE TITLE
Conformiteitseis additionele interfaces

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#53]
Er zullen extra eisen moeten gelden aan additionele interfaces, zoals webinterfaces. Concreet voorbeeld: we hebben onlangs gezien dat veel Webcams en inverters slecht beveiligd zijn. Criteria opstellen waaraan ze minimaal moeten voldoen.

**Comment by Sander3003** [comment]
Conformiteitseisen in 5.4 zijn beschreven voor alle interfaces.
