### ISSUE TITLE
Conformiteitseisen voor andersoortige connecties met dezelfde interface

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#54]
Vanuit Security t.b.v. conformiteitsbepalingen: Als de (IP) interface ook verbindt met bijvoorbeeld een leveranciers-cloud-platform, dan moet het cloud-platform worden ge-PEN-test. Dit geldt voor cloud-platforms met > t.b.d. kW totale opwerk.

Bij het gebruik van een gateway, geldt het bovenstaande eveneens, aangezien er eisen mogen worden gesteld aan de functie voor het reduceren van vermogen. Echter: het kan worden aangetoond dat de leveranciersfunctie voor het reduceren van vermogen is ge-PEN-test door een gerenommeerde (t.b.d) instantie.

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#34
