### ISSUE TITLE
61850 test functie

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#56]
Is er behoeft aan een test functie zoals IEC61850 mogelijk is?

**Comment by Sander3003** [comment]
@wp-alliander

**Comment by bw-alliander** [comment]
Wat doet zo'n testfunctie?

**Comment by Sander3003** [comment]
Met IEC61850 kan je bijvoorbeeld test operaties uitvoeren (61850-7-2:2010). Dit is niet nodig voor deze use-case. Het functioneel hebben van het systeem ligt bij de systeem eigenaar. Het staat de systeem eigenaar vrij om test functionaliteit in te bouwen.
