### ISSUE TITLE
Hebben we logging nodig?

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#59]
Mogelijkheid in IEC61850

**Comment by Sander3003** [comment]
@bw-alliander

**Comment by bw-alliander** [comment]
Goed punt, ik neem aan dat hier decentrale logging bedoeld wordt.

Ik denk dat het essentieel is om te weten wat de productieeenheden autonoom voor beslissingen nemen, als autonoom congestie opgelost wordt maar dit wordt niet gelogd is er naderhand geen manier om te zien dat er congestie was.

Ruw voorstel zou zijn dat productieeenheden een log bijhouden van puur meetdata en acties, met een interval van 5 minuten, in een roterend log van minstens 12h, welke uitgevraagd kan worden.
Deze data hoeft niet verzameld te worden als de productieeenheid niet kan produceren maar moet wel opgeslagen worden.
Dus bij stroomuitval moet na de stroomuitval de data ervoor en erna beschikbaar zijn, maar tijdens de uitval mag ontbreken, idem met 's nachts voor zon etc.

Volgens mij zit je dan aan een opslag van:
4 byte voor een timestamp, max 9x 4 bytes voor metingen (3 fase, 3 waardes), en een 16 bytes voor productiewaardes en acties van de installatie, komt neer op 56, zeg 64 bytes per 5 minuten.
Wat neerkomt op net onder de 8 kilobyte voor een 12 uur periode.
Dat klinkt niet als een onredelijke hoeveelheid data voor logging.

**Comment by Sander3003** [comment]
Buffered reporting kan in bovenstaande worden gerealiseerd.
