### ISSUE TITLE
Tijdstempel

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#6]
Verzoek vanuit werkgroep Netbeheer Nederland, Imprelementatie Europeese codes (iec) om zelf met een voorstel te komen over tijdstempel. Volgens mij is in de Duitse specificatie dit terug te vinden.

**Comment by Laurentjg** [comment]
De Duitse specificatie verwijst naar IEC 61850-7-2. Voor de semantiek beschrijft paragraaf 6.1.2.9. de syntax en attributen. Daarnaast stelt de Duitse specificatie dat hierin de kwaliteitsattributen "LeapSecondsKnown=TRUE", "ClockFailure" wordt gebruikt zoals bedoeld, "ClockNotSynchronized" wordt gebruikt zoals bedoeld, "TimeAccuracy=1". 

Met betrekking tot de TimeAccuracy is nog een besluit te maken of we aan de 2 seconden houden (kostenoverweging hardware), of conformeren aan de Duitse implementatie.

To do is integratie in ons informatiemodel.

**Comment by Laurentjg** [comment]
_Van externe reviewer rol NetManagement_ m.b.t. vraag of 2 seconde voldoende is: ligt aan de categorie..als deze toch meetwaarden doorgeeft, kan internet tijdsynchronisatie periodiek op de dag plaats vinden..dus mogelijk hoeft het niet zo'n probleem te zijn.

**Comment by Sander3003** [comment]
Zie keuze tijdsafwijking (zie bijlage).
