### ISSUE TITLE
IP traffic op private lijnen

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#7]
Bij het ontwerp ontstaat er IP verkeer op private verbindingen (bijvoorbeeld DSL thuisaansluitingen). Mogelijk een punt van aandacht.

**Comment by Sander3003** [comment]
Hoe kan een eindgebruikers zien of er connectie is? Troubleshooting?

**Comment by Sander3003** [comment]
Private verbinding: Vanuit deze specificatie geldt geen verplichting voor de "procumenten" om de connectie werkelijk aan te gaan sluiten op hun privé internetverbinding. Dus het accepteren van het gebruik van deze internetverbinding zal in product- of servicevoorwaarden moeten terugkeren, niet in deze specificatie.
Connectie aanwezigheid: Verwerkt in Conformiteitseisen
