### ISSUE TITLE
Keepalive frequentie

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#70]
Wat moet de keepalive frequentie zijn?

**Comment by Sander3003** [comment]
@bw-alliander

**Comment by bw-alliander** [comment]
Hmm, dat is vrij sterk afhankelijk van de individuele gebruikte verbinding, gezien dat hier belachelijk veel willekeurige netwerkapparatuur tussen zal zitten is het een moeilijk puntje.

In principe is het verbonden houden van een apparaat een taak voor het apparaat zelf (gezien het platform niet kan verbinden) dus dat zou daar een (automatische?) setting moeten zijn.

Een default van 2 minuten zou een goed begin zijn, maar kan zijn dat voor sommige netwerken dit te lang is, dus wellicht automatisch inkorten als er timeouts optreden.
Er is niet echt een goede manier om timeout tijden te bepalen, behalve live op de verbinding zelf...

**Comment by Sander3003** [comment]
Het zou mooi zijn als de keepalive signaal frequrentie wordt afgestemd op het gedrag van het publieke netwerk.

**Comment by Sander3003** [comment]
Zie 5.1

**Comment by bw-alliander** [comment]
Goed punt, had deze na de commit best dicht kunnen gooien.
