### ISSUE TITLE
Opgeslagen IP adressen

### ISSUE THREAD

**Issue by Laurentjg** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#8]
In de constructie zal, om verbinding te kunnen maken, IP adressen moeten worden gepersisteerd. Is dit acceptabel?
Overwegingen:
- Privacy
- Vergelijk gedrag op websites algemeen.

**Comment by Sander3003** [comment]
IPv4 en IPv6?

**Comment by Laurentjg** [comment]
Uiteindelijk toekomstvast (in lijn met Duitse specs) Dual-stack IPv4 **en** IPv6.

**Comment by Sander3003** [comment]
In de huidige opzet zal de elektriciteitsproductie eenheid het IP/DNS adres van de operational DER control moeten onthouden.

**Comment by Sander3003** [comment]
Issue open houden voor aandacht tijdens de detail specificatie.

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#11

**Comment by Sander3003** [comment]
Issue was moved to the Alliander fork.
