### ISSUE TITLE
Hoe voorkomen we dat klanten met opwek niet willen registreren ?

### ISSUE THREAD

**Issue by koenver** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#85]
Nu zien we al dat bepaalde klanten met Solar opwek in Klein Verbruik, de slimme meter weigeren.
(Dit ivm mogelijke minder interessante verrekening m.b.t. de salderingsregeling).
Dit risico bestaat natuurlijk nu ook m.b.t. RfG.  De enigste manier om dit in beeld te krijgen, zou bij slimme meters checken of de ODN registers (Opwek door Klant) kWhr standen hebben .

**Comment by Sander3003** [comment]
#42
