### ISSUE TITLE
Voeding voor eventuele externe modem

### ISSUE THREAD

**Issue by bartluijkx** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#88]
Als een productie eenheid geschikt is voor een black start, moet naast de interface een spanningsuitgang zijn voor een gateway.

Rationale: Daarmee is geen batterij pakket nodig voor de lokale functionaliteit (van de netbeheerder).

**Comment by Laurentjg** [comment]
De verwachting is dat RfG type A en RfG type B (dus tot 50MW) niet actief zullen bijdragen bij de eerste fases van de black-start. Reden is dat deze eenheden relatief "diep" in het net zitten en vaak E-netwerktechnisch niet gescheiden kunnen worden ingekoppeld. M.a.w. ze kunnen vaak allen maar i.c.m. òòk de grotere belastingen weer gekoppeld worden. Voor type C en D is dit waarschijnlijk anders, maar die worden hier niet beschreven. Wat gebeurt er dan wel? De netspanning komt op een netdeel en RfG type A schaalt autonoom langzaam op na inspectie of spanning en frequentie stabiel zijn (is eis RfG). Type B mag ook automatisch inschakelen o.b.v. vooraf vastgestelde voorwaarden. Er is dus **geen expliciet extern** vrijgave signaal nodig. Dit betekent dat het autonome gedrag dus zelf stuurt. De telecom komt op met het herstel van het net waarna het autonome gedrag, indien zo gewenst, kan worden beïnvloed. Zie #89. @bartluijkx zou een 230V voedingspunt (zonder batterij) dan voldoende zijn om daarmee ook de maatschappelijke kosten te beperken?

**Comment by bartluijkx** [comment]
Ja, een 230V voedingspunt (zonder batterij) is voorlopig voldoende om de maatschappelijke kosten beperkt te houden.

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#23
