### ISSUE TITLE
Voorrang van commando’s van de netbeheer 

### ISSUE THREAD

**Issue by bartluijkx** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#89]
Voorrang van commando’s van de netbeheer boven commando's van andere partijen (klanten, virtual aggregator) en commando's van autonoom gedrag van het eigen apparaat.

**Comment by Laurentjg** [comment]
Hierbij gelden de volgende overwegingen:
a) In een normale situatie, gaat het DSO (externe signaal) voor t.o.v. autonoom gedrag.
b) Bij geen communicatie zullen al gecommuniceerde schedules planmatig worden uitgevoerd.
c) Bij opstarten zal een "opstart-schedule" worden uitgevoerd, conform gespecificeerd in RfG.
d) Stel: iemand krijgt tòch onbevoegd controle over de interface-functies, dan koppelen we de externe sturing af en zal na een nieuw-start van de elektriciteitsproductie-eenheid weer voorspelbaar gedrag vertoont worden.
e) Stel: iemand krijgt tòch onbevoegd toegang krijgt tot de firmware van de elektriciteitproductie-eenheid van één bepaalde leverancier, dan kan deze persoon ongewenst stuurgedrag veroorzaken, maar tevens het externe signaal van de DSO blokkeren.  Dit is een probleem, maar van toepassing op een sub-set van één merk in het net. Moet door leverancier's firmware en patching-beleid worden opgevangen. Dit is tevens een conformiteitseis die wij stellen.

Dit is in lijn met de Duitse implementatie, waarbij de volgende volgorde is gekozen:
* System Reserve
* Marktsturing-functies
* Softstart
* Reguliere sturing DSO
* Communicatieuitval
* Noodsturing DSO

Verdere uitwerking in detailspecificatie.

**Comment by Sander3003** [comment]
This issue was moved to Alliander/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#22
