### ISSUE TITLE
Review commentaar: Algemeen,EU, protocol en IEC61850

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#91]
@phoutman

Algemeen
Ik zie dat dit document volledig geschreven is vanuit de netbeheerdersrol en behoefte. Het is enorm belangrijk om ook de consument mee te nemen. Het vertrouwen in de netbeheerders is al niet heel erg groot, na alle commotie rondom de slimme meter. Dit hele project betekent dat als een netbeheerder bij een consument zonnepanelen afschakelt, de consument geld misloopt. Mogelijk wordt dat op één of andere manier gecompenseerd, maar dat is nog niet bekend. Het gaat denk ik te ver om van de consumenten te vragen om de netbeheerders maar te vertrouwen op dit punt. Het gaat om geld, dus moet het door alle betrokken partijen gecontroleerd kunnen worden.
Dat betekent dat alle acties in het apparaat wat de opwek af- en aanschakelt niet alleen voor langere tijd gelogd moeten worden,het moet ook nog in te zien zijn door de bewoner.  

2.1 Informatie uit overige EU landen
               Duitsland, FNN Steuerbox
•	Kleine toevoeging: Er is niet alleen gekeken naar lokale congesties, maar ook op TSO niveau.
•	Rollen voor o.a. software updates zijn wel gedefinieerd, dit valt onder de Gateway Administrator rol. 
•	Voor de BSI is security het uitgangspunt geweest voor het ontwerp van de communicatie, afzonderlijke rollen, authenticatie en autorisatie.
Dit heeft geresulteerd in een zeer veilig, maar ook complex proces om verbinding te kunnen maken met een Steuerbox.
•	Wat ook meegenomen is (maar nog niet volledig uitgewerkt), is dat een consument zelf kan bepalen welke partij welke data mag zien en wie welke bevoegdheden heeft (bijvoorbeeld schakelen).
Dit is gedaan om a) de consument controle te geven over de eigen data en b) om het mogelijk te maken voor consumenten om zich te verenigen in een partij die energie verkoopt.
Hiermee kan een derde partij de mogelijkheid krijgen om opwek aan en af te schakelen als het economisch gunstig is. 

5.5 Registratie protocol
Ik ben erg blij dat hier gekozen wordt voor een centraal systeem, daar is in Duitsland niet voor gekozen en dat heeft het geheel echt extreem complex gemaakt.

Bijlage 2 – Evaluatie geschiktheid Standaarden

EFI: Een voordeel van EFI is dat er hele goede profielen van apparaten in zitten. Er wordt rekening gehouden met dingen als ramp-up time/ramp-down (bv generator), capaciteit, vulgraad (accu)
en vele andere aspecten. Op het moment dat er extern meer gestuurd gaat worden op netstabiliteit door ook verbruik te beïnvloeden kan dit heel veel helpen. Eigenlijk hebben ze in 4 profielen alle mogelijkheden beschreven. Ik ben het er mee eens dat EFI als protocol niet heel erg goed past, maar er kan wel heel veel van geleerd worden.

Het valt me hier ook op dat bepaalde protocollen negatief beoordeeld worden op het punt security, maar dat wordt weggelaten bij 61850. Ook 61850 heeft geen enkele beveiliging ingebouwd. Alles omtrent security moet er dus omheen gebouwd worden.

**Comment by Laurentjg** [comment]
Deel "2.1 Informatie uit overige EU landen" verwerkt in Updates_buurlanden-patch-1

**Comment by Sander3003** [comment]
@Laurentjg controleerbaarheid procumers hebben we nog niet geadresseerd. De vraag is even hoever we hier in in willen gaan. blockchain technologie gaat misschien wat te ver (misschien ook niet). We kunnen fabrikanten ook adviseren om zelf een log bij te houden zodat klanten het systeembeheer gedrag kunnen inzien. Andere optie is dat de systeembeheerder zelf dit logt en beschikbaar maakt aan de klant.

**Comment by Laurentjg** [comment]
Geadviseerd punt toegevoegd aan conformiteit, zie gerelateerd pullrequest.

**Comment by Sander3003** [comment]
@phoutman we hebben geprobeerd al je punten te verwerken in het document. Dank voor je input!
