### ISSUE TITLE
Elektriciteitsproductie-eenheid-gebruikers moeten zelf controle hebben welke data gedeeld wordt

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#92]
Idee: #91

1. De gebruiker moet kunnen kiezen met wie de informatie wordt gedeeld (Doen ze mee met het oplossen van problemen door deze interface of niet).
2. De gebruiker moet zelf kunnen kiezen met welke partijen de data wordt gedeeld.
3. De gebruiker moetn kunnen kiezen welke informatie met andere partijen wordt gedeeld.

**Comment by Laurentjg** [comment]
Als requirement 22 toegevoegd.
