### ISSUE TITLE
Kan een huis al een elektriciteitsproductie eenheid worden beschouwd?

### ISSUE THREAD

**Issue by Sander3003** [NetbeheerNederland/Interfacespecificatie-elektriciteit-productie-eenheden-RfG#94]
CENELEC TC 205 kent een CEM concept (customer energy manager). Deze CEM stuurt de apparaten aan in bijvoorbeeld je huis om flexibiliteit te ontsluiten. Deze CEM kunnen we beschouwen als gateway zoals gespecificeerd in dit document. Dit mag alleen als deze binnen de definitie elektriciteitsproductie-eenheid past. Voldoet deze interface specificatie aan de TC 207 standaarden in wording?

**Comment by Laurentjg** [comment]
- volgens RfG lijkt meer de "elektriciteitproductie-**installatie**" op hetgeen hier boven beschreven wordt. In deze fase, sturen we alleen de **eenheden** aan. Het is echter wel denkbaar dat de beschreven gateways in de toekomst ook meerdere eenheden gaat aansturen. Nog sterker: dit gaat de voordelen bieden dat binnen het "huis" kan worden geregeld wat de maximale belasting of opwek is die over de aansluiting mag gaan lopen.

**Comment by Sander3003** [comment]
De definities zijn wat onduidelijk: https://netbeheernederland.gitbooks.io/interfacespecificatie-elektriciteit/content/bijlage_1__rfg,_dcc_en_gl_so_artikelen_met_relatie/

@wilcowijbrandi Doordat de definities niet geheel duidelijk zijn kan niet definitief worden vastgesteld of een gebouw of woning als elektriciteitsproductie-eenheid kan worden gezien. Het lijkt erop dat dit niet zomaar mag.  Mogelijk brengt toekomstige EU regelgeving hier meer mogelijkheden om zodoende aan te sluiten bij de TC207.
